services:
  postgres:
    image: postgres:14.5-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: reza3452
      POSTGRES_DB: next-match
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql